# Use root/example as user/password credentials
version: '3.1'

services:
  db:
    image: mongo
    restart: always
    ports:
      - "27018:27017"
    volumes:
      - //C/Program Files/MongoDB/Server/6.0/data:/data/db
    
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - "3000:3000"
    depends_on:
      - db
    links:
      - db
